# Generated by Django 4.1.2 on 2022-10-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nooz2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Nooz', max_length=255),
        ),
    ]
