# Generated by Django 4.1.2 on 2022-10-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nooz2', '0003_post_timestamp_alter_post_title_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='News', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='Click above to read more', max_length=50),
        ),
    ]
