# Generated by Django 4.1.2 on 2022-10-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nooz2', '0005_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='News', max_length=255),
        ),
    ]
