# Generated by Django 4.1.2 on 2022-10-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nooz2', '0008_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
