# Generated by Django 4.1.2 on 2022-11-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nooz2', '0017_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
